export { default as HeroIllustration } from './HeroIllustration';
export { default as AboutIllustration } from './AboutIllustration';
export { default as ContactIllustration } from './ContactIllustration';
export { default as ProductIllustration } from './ProductIllustration';
export { default as ProductCard } from './ProductCard';
export { default as TeamIllustration } from './TeamIllustration';
export { default as AdminIllustration } from './AdminIllustration';
export { default as ProductDetailIllustration } from './ProductDetailIllustration';
export { default as TimelineIllustration } from './TimelineIllustration'; 